# Generated by Django 2.2.4 on 2020-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20200322_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='videolink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, upload_to='learn/videos'),
        ),
    ]
