# Generated by Django 2.2.4 on 2020-04-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200322_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['weeklyclass', 'num']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-year', 'semester', 'title']},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['chapter', 'num']},
        ),
        migrations.AlterModelOptions(
            name='weeklyclass',
            options={'ordering': ['-classroom', 'num']},
        ),
    ]
